spring:
  application:
    name: payment-service


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://payment-service-postgres:5432/payment_service_db
    username: admin
    password: password

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.use_sql_comments: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-consumer-group
    topic:
      payment-client-sender

    admin:
      auto-create: true
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1


