spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: admin
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.use_sql_comments: true
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
      bootstrapServers:
        - localhost:9092
      topics:
        - name: "payment-command"
          partitions: 1
          replication-factor: 1
        - name: "payment-command-result"
          partitions: 1
          replication-factor: 1




